version: "3.9"

services:
  lexer_gui:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true  # Allows GUI apps to interact with X server
